"""created notifications for comment, commentLike

Revision ID: 2c511eb97135
Revises: d7f625ebd3f7
Create Date: 2024-05-08 12:39:43.201135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c511eb97135'
down_revision = 'd7f625ebd3f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_like_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('reciever_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_comment_like_notifications_comment_id_comments')),
    sa.ForeignKeyConstraint(['reciever_id'], ['users.id'], name=op.f('fk_comment_like_notifications_reciever_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_comment_like_notifications_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_like_notifications'))
    )
    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isLiked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_comment_likes_comment_id_comments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comment_likes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_likes'))
    )
    op.create_table('comment_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isLiked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('reciever_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_comment_notifications_comment_id_comments')),
    sa.ForeignKeyConstraint(['reciever_id'], ['users.id'], name=op.f('fk_comment_notifications_reciever_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_comment_notifications_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_notifications'))
    )
    op.drop_table('commentlikes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentlikes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('isLiked', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('comment_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='fk_commentlikes_comment_id_comments'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_commentlikes_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_commentlikes')
    )
    op.drop_table('comment_notifications')
    op.drop_table('comment_likes')
    op.drop_table('comment_like_notifications')
    # ### end Alembic commands ###
