"""added image_src column for post table

Revision ID: 3b8d25914140
Revises: 4133c3e41f8f
Create Date: 2024-04-25 12:27:00.245185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8d25914140'
down_revision = '4133c3e41f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_image_src', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('_image_src')

    # ### end Alembic commands ###
