"""added friendship_id foreign key to friend_request_notifications table

Revision ID: 496bfb45b6a9
Revises: a763f54da88a
Create Date: 2024-05-06 13:41:33.165430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496bfb45b6a9'
down_revision = 'a763f54da88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_request_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friendship_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_friend_request_notifications_friendship_id_friendships'), 'friendships', ['friendship_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_request_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_friend_request_notifications_friendship_id_friendships'), type_='foreignkey')
        batch_op.drop_column('friendship_id')

    # ### end Alembic commands ###
