"""added unique constraints on notification

Revision ID: 5f341f5778bd
Revises: fe249fee97d6
Create Date: 2024-04-10 18:38:37.183808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f341f5778bd'
down_revision = 'fe249fee97d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_unique_constraint('notification_uniqueness', ['notification_sender_id', 'notification_reciever_id', 'text', 'notification_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('notification_uniqueness', type_='unique')

    # ### end Alembic commands ###
