"""added dark mode to user table

Revision ID: 94450bc2a4c4
Revises: 954ff52d11e1
Create Date: 2024-05-16 22:06:11.346954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94450bc2a4c4'
down_revision = '954ff52d11e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isDark', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isDark')

    # ### end Alembic commands ###
