"""added text for commentnotification

Revision ID: 954ff52d11e1
Revises: aefbb8aa499f
Create Date: 2024-05-08 13:57:04.964110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954ff52d11e1'
down_revision = 'aefbb8aa499f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(), nullable=False))
        batch_op.drop_column('isLiked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isLiked', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###
