"""changed notification type to a different name

Revision ID: 9ab9e7a92a38
Revises: ccff11426235
Create Date: 2024-04-07 09:18:44.318690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab9e7a92a38'
down_revision = 'ccff11426235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('_notification_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_notification_type', sa.VARCHAR(length=14), nullable=True))

    # ### end Alembic commands ###
