"""got rid of table args for all notifications

Revision ID: aefbb8aa499f
Revises: 2c511eb97135
Create Date: 2024-05-08 13:41:05.426699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aefbb8aa499f'
down_revision = '2c511eb97135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_like_notifications', schema=None) as batch_op:
        batch_op.drop_constraint('notification_uniqueness', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_like_notifications', schema=None) as batch_op:
        batch_op.create_unique_constraint('notification_uniqueness', ['sender_id', 'reciever_id', 'text'])

    # ### end Alembic commands ###
