"""init

Revision ID: c46ac3dd1941
Revises: 
Create Date: 2024-04-07 13:21:16.998284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46ac3dd1941'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('reciever_id', sa.Integer(), nullable=False),
    sa.Column('_status', sa.Enum('pending', 'accepted', 'rejected', name='friendship_status'), nullable=True),
    sa.ForeignKeyConstraint(['reciever_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_sender_id', sa.Integer(), nullable=False),
    sa.Column('notification_reciever_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['notification_reciever_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['notification_sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('friendships')
    op.drop_table('users')
    # ### end Alembic commands ###
