"""added notifications table and editted foreign keys in Friendship to nullable False

Revision ID: ccff11426235
Revises: fbc9d6a66688
Create Date: 2024-04-01 21:02:23.325912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccff11426235'
down_revision = 'fbc9d6a66688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_friendships')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_friendships',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('reciever_id', sa.INTEGER(), nullable=False),
    sa.Column('_status', sa.VARCHAR(length=8), nullable=True),
    sa.ForeignKeyConstraint(['reciever_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
