"""added postlikenotification table

Revision ID: d7f625ebd3f7
Revises: 496bfb45b6a9
Create Date: 2024-05-07 18:00:44.669171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f625ebd3f7'
down_revision = '496bfb45b6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_like_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('reciever_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_like_notifications_post_id_posts')),
    sa.ForeignKeyConstraint(['reciever_id'], ['users.id'], name=op.f('fk_post_like_notifications_reciever_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_post_like_notifications_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_like_notifications')),
    sa.UniqueConstraint('sender_id', 'reciever_id', 'text', name='notification_uniqueness')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_like_notifications')
    # ### end Alembic commands ###
