"""init

Revision ID: fbc9d6a66688
Revises: 
Create Date: 2024-03-31 20:14:11.376563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc9d6a66688'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('reciever_id', sa.Integer(), nullable=True),
    sa.Column('_status', sa.Enum('pending', 'accepted', 'rejected', name='friendship_status'), nullable=True),
    sa.ForeignKeyConstraint(['reciever_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    op.drop_table('users')
    # ### end Alembic commands ###
