"""added unique constraints on friendship foreign keys

Revision ID: fe249fee97d6
Revises: e748ae20603d
Create Date: 2024-04-09 11:52:20.849028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe249fee97d6'
down_revision = 'e748ae20603d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_friendships')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_foreign_keys', ['sender_id', 'reciever_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_constraint('unique_foreign_keys', type_='unique')

    op.create_table('_alembic_tmp_friendships',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('reciever_id', sa.INTEGER(), nullable=False),
    sa.Column('_status', sa.VARCHAR(length=8), nullable=True),
    sa.ForeignKeyConstraint(['reciever_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'reciever_id', name='unique_foreign_keys')
    )
    # ### end Alembic commands ###
